encoding:          utf-8
language:          zh-CN
timezone:          Asia/Shanghai
version:
  css:             0.4.1
  js:              0.4.0
beian:             鲁ICP备17026272号-3
url:               "https://blog.mizore.cn"
pygments:          true
permalink:         pretty
author:            Mizore
title:             "Mizore's blog"
permalink:         /:title.html
paginate:          10
paginate_path:     /page:num/
excerpt_separator: <!--more-->
markdown:          kramdown
kramdown:
  input:           GFM
highlighter:       rouge
plugins:
  - jekyll-sitemap
defaults:
  -
    values:
      layout:      post
      copy:        true
      comment:     false
