encoding:          UTF-8
timezone:          Asia/Shanghai
version:
  css:             0.6.3
  js:              0.6.5
beian:             鲁ICP备17026272号-3
url:               "https://blog.mizore.cn"
pygments:          true
permalink:         pretty
author:            Mizore
title:             "Mizore's blog"
permalink:         /:title.html
paginate:          20
paginate_path:     /page:num/
excerpt_separator: <!--more-->
markdown:          kramdown
kramdown:
  input:           GFM
highlighter:       rouge
plugins:
  - jekyll-sitemap
defaults:
  -
    values:
      layout:      post
      copy:        true
      comment:     false
      lang:        zh-CN
