pygments:           true
permalink:          pretty
author:             Mizore
title:              "Mizore's blog"
permalink:          /:title.html
paginate:           7
paginate_path:      /page:num
excerpt_separator:  <!--more-->
markdown:           Redcarpet
highlighter:        rouge
encoding:           utf-8
language:           zh-cn
timezone:           Asia/Shanghai
version:            0.1.8.2
beian:              鲁ICP备17026272号-3